algorithm: mpl
save_dir: ./saved_models/usb_audio
save_name: mpl_superbks_50_0
resume: True
load_path: ./saved_models/usb_audio/mpl_superbks_50_0/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 100
num_train_iter: 102400
num_eval_iter: 2048
num_warmup_iter: 5120
num_labels: 50
batch_size: 8
eval_batch_size: 16
tsa_schedule: none
T: 0.7
p_cutoff: 0.6
ulb_loss_ratio: 8.0
teacher_lr: 0.03
label_smoothing: 0.1
num_uda_warmup_iter: 5000
num_stu_wait_iter: 3000
uratio: 1
use_cat: False
ema_m: 0.0
optim: AdamW
lr: 2e-05
momentum: 0.9
weight_decay: 2e-05
amp: False
clip: 0.0
net: wave2vecv2_base
net_from_name: False
data_dir: ./data
dataset: superbks
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
max_length_seconds: 1.0
sample_rate: 16000
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10060
dist_backend: nccl
gpu: None
